const tg=window.Telegram?.WebApp||null;if(tg){tg.ready();tg.expand();}
const state={config:null,items:[],found:[]};const $=s=>document.querySelector(s);const init=()=>tg?.initData||'';
async function api(url,opt={}){const headers={'content-type':'application/json',...(opt.headers||{})};if(init())headers['x-telegram-init-data']=init();const r=await fetch(url,{...opt,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Ошибка запроса');return d;}
function toast(text,error){const x=$('#toast');x.textContent=text;x.className=error?'show error':'show';setTimeout(()=>x.className='',3200);}
function card(x,select){const c=state.config.collections.find(y=>y.id===x.collectionId);const visual=x.image?'<img src="'+x.image+'">':'<div class="artfake" style="--a:'+(c?.accent||'#ffcf40')+'">✦<small>#'+(x.number||'NFT')+'</small></div>';return '<article><div class="art">'+visual+'<label>#'+(x.number||'—')+'</label></div><div class="body"><b>'+x.name+'</b><small>'+(c?.name||'NFT')+'</small><div class="bottom"><span>★ '+x.dailyStars+' / день</span>'+(select?'<input type="checkbox" data-id="'+x.id+'">':'<button data-rent="'+x.id+'">Арендовать</button>')+'</div></div></article>';}
function render(){const filter=$('#filter').value;const items=state.items.filter(x=>!filter||x.collectionId===filter);$('#grid').innerHTML=items.map(x=>card(x,false)).join('');$('#empty').classList.toggle('hidden',items.length>0);document.querySelectorAll('[data-rent]').forEach(b=>b.onclick=()=>rent(b.dataset.rent));}
async function rent(id){const days=prompt('Срок аренды в днях','1');if(days===null)return;try{const d=await api('/api/rentals/invoice',{method:'POST',body:JSON.stringify({itemId:id,days:Number(days)})});if(tg)tg.openInvoice(d.invoiceLink,s=>s==='paid'&&toast('Оплата прошла'));else window.open(d.invoiceLink,'_blank');}catch(e){toast(e.message,true);}}
async function inspect(){try{const d=await api('/api/wallet/inspect',{method:'POST',body:JSON.stringify({walletAddress:$('#wallet').value.trim()})});state.found=d.items||[];$('#message').textContent=d.message;$('#found').classList.toggle('hidden',!state.found.length);$('#foundGrid').innerHTML=state.found.map(x=>card(x,true)).join('');}catch(e){$('#message').textContent=e.message;}}
async function add(){const items=[...document.querySelectorAll('[data-id]:checked')].map(x=>state.found.find(y=>y.id===x.dataset.id)).filter(Boolean);if(!items.length)return toast('Выберите NFT',true);try{const d=await api('/api/admin/inventory',{method:'POST',body:JSON.stringify({walletAddress:$('#wallet').value.trim(),items})});toast('Добавлено: '+d.added);state.items=(await api('/api/inventory')).items;render();}catch(e){toast(e.message,true);}}
async function boot(){try{state.config=await api('/api/config');state.items=(await api('/api/inventory')).items;const v=state.config.viewer;$('#profile').textContent=v?.username?'@'+v.username:'Telegram';$('.admin').classList.toggle('hidden',!v?.isAdmin);$('#available').textContent=state.config.stats.available;$('#rented').textContent=state.config.stats.rented;$('#filter').innerHTML='<option value="">Все коллекции</option>'+state.config.collections.map(x=>'<option value="'+x.id+'">'+x.name+'</option>').join('');render();$('#filter').onchange=render;$('#inspect').onclick=inspect;$('#add').onclick=add;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#catalog').classList.toggle('hidden',b.dataset.view!=='catalog');$('#topup').classList.toggle('hidden',b.dataset.view!=='topup');});}catch(e){toast(e.message,true);}}boot();
