const tg=window.Telegram?.WebApp||null;if(tg){tg.ready();tg.expand();}
const params=new URLSearchParams(location.search);const passedApi=params.get('api');if(passedApi)localStorage.setItem('starrent_api_url',passedApi);const API=(localStorage.getItem('starrent_api_url')||'').replace(/\/$/,'');
const state={config:null,items:[],found:[],search:'',filter:''};const $=s=>document.querySelector(s);const init=()=>tg?.initData||'';
async function api(url,opt={}){const headers={'content-type':'application/json',...(opt.headers||{})};if(init())headers['x-telegram-init-data']=init();const r=await fetch(API+url,{...opt,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Ошибка запроса');return d;}
function toast(text,error){const x=$('#toast');x.textContent=text;x.className=error?'show error':'show';setTimeout(()=>x.className='',3200);}
function safe(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function card(x,select){const c=state.config.collections.find(y=>y.id===x.collectionId);const visual=x.image?'<img src="'+safe(x.image)+'" alt="'+safe(x.name)+'">':'<div class="artfake" style="--a:'+(c?.accent||'#ffcf40')+'"><span>✦</span><small>#'+safe(x.number||'NFT')+'</small></div>';return '<article class="nft-card"><div class="art">'+visual+'<label>#'+safe(x.number||'—')+'</label><div class="term">1–180 дн.</div></div><div class="card-body"><div class="card-name">'+safe(x.name)+'</div><div class="card-collection">'+safe(c?.name||'NFT')+'</div><div class="card-bottom"><div class="price"><b>★ '+x.dailyStars+'</b><span>/ день</span></div>'+(select?'<label class="checkbox"><input type="checkbox" data-id="'+safe(x.id)+'"><i></i></label>':'<button class="rent" data-rent="'+safe(x.id)+'">Арендовать</button>')+'</div></div></article>';}
function render(){const list=state.items.filter(x=>(!state.filter||x.collectionId===state.filter)&&(!state.search||x.name.toLowerCase().includes(state.search.toLowerCase())));$('#grid').innerHTML=list.map(x=>card(x,false)).join('');$('#empty').classList.toggle('hidden',list.length>0);document.querySelectorAll('[data-rent]').forEach(b=>b.onclick=()=>rent(b.dataset.rent));}
function renderChips(){const all=[{id:'',name:'Все'}].concat(state.config.collections);$('#collectionChips').innerHTML=all.map(c=>'<button class="chip '+(c.id===state.filter?'active':'')+'" data-chip="'+c.id+'">'+c.name+'</button>').join('');document.querySelectorAll('[data-chip]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.chip;$('#filter').value=state.filter;renderChips();render();});}
async function rent(id){const days=prompt('Срок аренды в днях','1');if(days===null)return;const n=Number(days);if(!Number.isInteger(n)||n<1||n>180)return toast('Укажи срок от 1 до 180 дней',true);try{const d=await api('/api/rentals/invoice',{method:'POST',body:JSON.stringify({itemId:id,days:n})});if(tg)tg.openInvoice(d.invoiceLink,s=>s==='paid'&&toast('Оплата прошла'));else window.open(d.invoiceLink,'_blank');}catch(e){toast(e.message,true);}}
async function inspect(){const wallet=$('#wallet').value.trim();if(!wallet)return toast('Вставь TON-адрес',true);$('#message').textContent='Проверяем кошелёк…';try{const d=await api('/api/wallet/inspect',{method:'POST',body:JSON.stringify({walletAddress:wallet})});state.found=d.items||[];$('#message').textContent=d.message;$('#found').classList.toggle('hidden',!state.found.length);$('#foundGrid').innerHTML=state.found.map(x=>card(x,true)).join('');}catch(e){$('#message').textContent=e.message;}}
async function add(){const items=[...document.querySelectorAll('[data-id]:checked')].map(x=>state.found.find(y=>y.id===x.dataset.id)).filter(Boolean);if(!items.length)return toast('Выбери NFT',true);try{const d=await api('/api/admin/inventory',{method:'POST',body:JSON.stringify({walletAddress:$('#wallet').value.trim(),items})});toast('Добавлено NFT: '+d.added);state.items=(await api('/api/inventory')).items;$('#available').textContent=state.items.length;render();}catch(e){toast(e.message,true);}}
async function boot(){try{state.config=await api('/api/config');state.items=(await api('/api/inventory')).items;const v=state.config.viewer;$('#profile').textContent=v?.username?'@'+v.username:'Telegram';$('.admin').classList.toggle('hidden',!v?.isAdmin);$('#available').textContent=state.config.stats.available;$('#rented').textContent=state.config.stats.rented;$('#filter').innerHTML='<option value="">Все коллекции</option>'+state.config.collections.map(x=>'<option value="'+x.id+'">'+safe(x.name)+'</option>').join('');renderChips();render();$('#filter').onchange=e=>{state.filter=e.target.value;renderChips();render();};$('#search').oninput=e=>{state.search=e.target.value;render();};$('#inspect').onclick=inspect;$('#add').onclick=add;$('#scrollCatalog').onclick=()=>$('#catalog').scrollIntoView({behavior:'smooth'});document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#catalog').classList.toggle('hidden',b.dataset.view!=='catalog');$('#topup').classList.toggle('hidden',b.dataset.view!=='topup');window.scrollTo({top:0,behavior:'smooth'});});}catch(e){toast('API недоступен: '+e.message,true);}}
boot();
